[package]
name = "native"
version = "0.1.0"
authors = ["Kiril Mihaylov <Kiril195@hotmail.com>"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
memory_c = []
kernel_mode = []

[dependencies.native_macros]
path = "native_macros"
